### ISSUE TITLE
什么是access_key？

### ISSUE THREAD

**Issue by OuyangWenyu** [zjf014/hydro-opendata#2]
你好，运行readme中示例代码，首先会提示输入一个access key，请问这个是什么意思？

![image](https://user-images.githubusercontent.com/10172837/231634902-4b662f96-bf7b-4445-84a9-1ed9bb64b391.png)

**Comment by zjf014** [comment]
通过api访问minio需要提供key和secret，由minio服务器管理员提供。
![image](https://user-images.githubusercontent.com/10348318/231646601-30b911ff-f41a-4730-84a3-09bb465f7dc7.png)

**Comment by OuyangWenyu** [comment]
输入了，继续报错了，是我输错了？还是我必须用自己的minio账号的key？这个key在哪里能找着呢？

![image](https://user-images.githubusercontent.com/10172837/231675518-03e8516a-3aa7-4880-930c-db0c6ac5e52f.png)

**Comment by OuyangWenyu** [comment]
minio已经处理好了
