### ISSUE TITLE
name 'hrefs' is not defined

### ISSUE THREAD

**Issue by silencesoup** [zjf014/hydro-opendata#5]
~/.conda/envs/test/lib/python3.9/site-packages/hydro_opendata/downloader/dem.py in download(self, save_dir, cover)
    104         '''
    105 
--> 106         if hrefs is not None:
    107 
    108             for href in hrefs:

这里函数形参里没定义hrefs，跑教程里的会报错，改成如下即可

def new_download(self, save_dir='.', hrefs = [], cover=False):
    ……

**Comment by zjf014** [comment]
收到
