### ISSUE TITLE
PermissionError: Forbidden

### ISSUE THREAD

**Issue by silencesoup** [zjf014/hydro-opendata#6]
PermissionError                           Traceback (most recent call last)
<ipython-input-3-47a449b1b6a8> in <module>
      3 
      4 # 指定数据集wis或camels
----> 5 gpm = GPMReader('camels')
      6 
      7 # 指定开始及结束时间

~/.conda/envs/test/lib/python3.9/site-packages/hydro_opendata/s3api/minio.py in __init__(self, dataset_name)
    398             self._dataset = 'camdata'
    399 
--> 400         with fs.open(os.path.join(bucket_name, f'{self._dataset}/gpm/gpm.json')) as f:
    401             cont = json.load(f)
    402             self._starttime = np.datetime64(cont['start'])

我登录minio看了下，好像/camdata/gpm文件夹下没有gpm.json，是因为这个文件额外加密设置访问权限了，还是什么其他原因？

**Comment by OuyangWenyu** [comment]
这个应该是minio的事，现在应该都解决了吧

**Comment by zjf014** [comment]
看下test/camdata/gpm/下能不能看到，不行的话应该是minio账号的权限问题
