### ISSUE TITLE
能否把对2004年-2015年GFS数据申请部分转换成代码

### ISSUE THREAD

**Issue by silencesoup** [zjf014/hydro-opendata#7]
现在只有GFS的2016年以后的数据
我昨晚试了一下，可以在这里向NOAA申请到最早2004年2月15日的GFS数据
https://www.ncei.noaa.gov/products/weather-climate-models/global-forecast
但是数据整体格式是压缩包，每一天的文件大约就要1.5G，且每次最多申请200G的数据，他会把数据获取的ftp连接发到邮箱里
能否把这部分数据整合到MINIO里

**Comment by zjf014** [comment]
可以分区域申请吗，比如camels数据集范围内的

**Comment by silencesoup** [comment]
好像不支持，目前应该暂时不需要了
